services:
  tiktok_embdedder:
    build:
      dockerfile: ./docker/tiktok_embedder/Dockerfile
    args:
      - build_tags=scrape
    container_name: tiktok_embedder
    environment:
      - DOMAIN=https://tt.yourdomain.tld
      - PORT=4232
      - FANCY_SLIDESHOW=false
      - PUBLIC=false
      - LIMIT_PUBLIC_AMOUNT=0
      - FFMPEG=false
      - GIN_MODE=release
      #- INSTALL_ID=your install id if you have gotten one from somewhere
    ports:
      - "4232:4232"
    networks:
      - tiktok_network
    volumes:
      - your path:/app/collages
      - /tmp/collages:/tmp/collages

  photo_collager:
    build:
      dockerfile: ./docker/photo_collager/Dockerfile
    container_name: photo_collager
    networks:
      - tiktok_network
    volumes:
      - your path:/app/collages
      - /tmp/collages:/tmp/collages

networks:
  tiktok_network:
    driver: bridge
